### ISSUE TITLE
24.04/Noble Numbat support

### ISSUE THREAD

**Issue by rasika-jay** [AdityaGarg8/t2-ubuntu-repo#10]
Any plans for 24.04/Noble Numbat?

[Noble Numbat Release Schedule](https://discourse.ubuntu.com/t/noble-numbat-release-schedule/35649)

**Comment by AdityaGarg8** [comment]
I will get it done on April 25, when it releases.

**Comment by rasika-jay** [comment]
hey @AdityaGarg8 thanks for updating, but there seems to be an issue. what am i doing wrong?

```
CODENAME=noble
curl -s --compressed "https://adityagarg8.github.io/t2-ubuntu-repo/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg >/dev/null
sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
echo "deb [signed-by=/etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg] https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/${CODENAME} ./" | sudo tee -a /etc/apt/sources.list.d/t2.list
sudo apt update
deb [signed-by=/etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg] https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/noble ./
Get:1 https://adityagarg8.github.io/t2-ubuntu-repo ./ InRelease [2119 B]
Hit:2 http://security.ubuntu.com/ubuntu noble-security InRelease
Get:3 https://adityagarg8.github.io/t2-ubuntu-repo ./ Packages [4809 B]
Ign:4 https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/noble ./ InRelease
Err:5 https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/noble ./ Release
  404  Not Found [IP: 20.26.156.215 443]
Hit:6 http://gb.archive.ubuntu.com/ubuntu noble InRelease
Hit:7 http://gb.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:8 http://gb.archive.ubuntu.com/ubuntu noble-backports InRelease
Reading package lists... Done
E: The repository 'https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/noble ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by AdityaGarg8** [comment]
> hey @AdityaGarg8 thanks for updating, but there seems to be an issue. what am i doing wrong?
> 
> ```
> CODENAME=noble
> curl -s --compressed "https://adityagarg8.github.io/t2-ubuntu-repo/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg >/dev/null
> sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
> echo "deb [signed-by=/etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg] https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/${CODENAME} ./" | sudo tee -a /etc/apt/sources.list.d/t2.list
> sudo apt update
> deb [signed-by=/etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg] https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/noble ./
> Get:1 https://adityagarg8.github.io/t2-ubuntu-repo ./ InRelease [2119 B]
> Hit:2 http://security.ubuntu.com/ubuntu noble-security InRelease
> Get:3 https://adityagarg8.github.io/t2-ubuntu-repo ./ Packages [4809 B]
> Ign:4 https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/noble ./ InRelease
> Err:5 https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/noble ./ Release
>   404  Not Found [IP: 20.26.156.215 443]
> Hit:6 http://gb.archive.ubuntu.com/ubuntu noble InRelease
> Hit:7 http://gb.archive.ubuntu.com/ubuntu noble-updates InRelease
> Hit:8 http://gb.archive.ubuntu.com/ubuntu noble-backports InRelease
> Reading package lists... Done
> E: The repository 'https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/noble ./ Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```

There is no deb in the repo, the kernels are still being compiled.

**Comment by AdityaGarg8** [comment]
You can try now

**Comment by AdityaGarg8** [comment]
I'm reopening this. You can close it when you get it working.

**Comment by rasika-jay** [comment]
yep, works now - thank you!
