### ISSUE TITLE
apt reporting this repository 'does not have a Release file.'

### ISSUE THREAD

**Issue by RobertGru** [AdityaGarg8/t2-ubuntu-repo#13]
Apt giving 'does not have a Relase file.' error message for this repository.  It 'is therefore disabled by default' by apt.

echo "deb [signed-by=/etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg] https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/${jammy} ./" | sudo tee -a /etc/apt/sources.list.d/t2.list
sudo apt update
deb [signed-by=/etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg] https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/ ./
Hit:1 https://packages.microsoft.com/repos/edge stable InRelease
Hit:2 https://adityagarg8.github.io/t2-ubuntu-repo ./ InRelease                                                             
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy InRelease                                                                   
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease                                            
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease                       
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]                 
Hit:7 https://dl.google.com/linux/chrome/deb stable InRelease                  
Ign:8 https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download ./ InRelease
**Err:9 https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download ./ Release
  404  Not Found [IP: 140.82.112.3 443]
Reading package lists... Done
E: The repository 'https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.**

**Comment by AdityaGarg8** [comment]
It's `jammy` not `${jammy}`

**Comment by AdityaGarg8** [comment]
```
sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
echo "deb [signed-by=/etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg] https://github.com/AdityaGarg8/t2-ubuntu-repo/releases/download/jammy ./" | sudo tee -a /etc/apt/sources.list.d/t2.list
sudo apt update
```

run this

**Comment by RobertGru** [comment]
Thank you very much.  Issue resolved.  Well, NOT an issue to begin with.  User error. :)
