### ISSUE TITLE
Touchbar does not work 

### ISSUE THREAD

**Issue by ysukhovey** [AdityaGarg8/t2-ubuntu-repo#7]
Touchbar does not work on Macbook Pro 18,2. Booting into MacOS (recovery and normal mode) does nothing.

>uname -a
>Linux maclinux 6.5.9-t2-mantic #1 SMP PREEMPT_DYNAMIC Wed Oct 25 18:07:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

>$ sudo tiny-dfr
>thread 'main' panicked at src/main.rs:639:43:
>called `Result::unwrap()` on an `Err` value: No touchbar device found
>note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

>$ lsusb
>Bus 007 Device 008: ID 05ac:8102 Apple, Inc. Touch Bar Backlight
>Bus 007 Device 007: ID 05ac:8302 Apple, Inc. Touch Bar Display
>Bus 007 Device 006: ID 05ac:027c Apple, Inc. Apple Internal Keyboard / Trackpad
>Bus 007 Device 005: ID 05ac:8103 Apple, Inc. Headset
>Bus 007 Device 004: ID 05ac:8262 Apple, Inc. Ambient Light Sensor
>Bus 007 Device 003: ID 05ac:8514 Apple, Inc. FaceTime HD Camera (Built-in)
>Bus 007 Device 002: ID 05ac:8233 Apple, Inc. iBridge
>Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
>Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
>Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
>Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
>Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
>Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
>Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by jstockdale** [comment]
I'm on noble, seeing this same issue, but I don't see all of the devices enumerated correctly on lsusb.

What did it end up being on your side @ysukhovey? Thanks!

```
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 007 Device 002: ID 05ac:8262 Apple, Inc. Ambient Light Sensor
Bus 007 Device 003: ID 05ac:0340 Apple, Inc. Apple Internal Keyboard / Trackpad
Bus 007 Device 004: ID 05ac:8104 Apple, Inc. 
```

```
jstockdale@jupiter:~$ uname -a
Linux jupiter 6.8.7-t2-noble #1 SMP PREEMPT_DYNAMIC Thu Apr 25 17:31:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by AdityaGarg8** [comment]
> I'm on noble, seeing this same issue, but I don't see all of the devices enumerated correctly on lsusb.
> 
> What did it end up being on your side @ysukhovey? Thanks!
> 
> ```
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 007 Device 002: ID 05ac:8262 Apple, Inc. Ambient Light Sensor
> Bus 007 Device 003: ID 05ac:0340 Apple, Inc. Apple Internal Keyboard / Trackpad
> Bus 007 Device 004: ID 05ac:8104 Apple, Inc. 
> ```
> 
>  ```
> jstockdale@jupiter:~$ uname -a
> Linux jupiter 6.8.7-t2-noble #1 SMP PREEMPT_DYNAMIC Thu Apr 25 17:31:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
> ```

Have you tried rebooting in macOS and then back to Linux?
